import { collectDossierResearch } from './research.mjs';
const BASE='https://api.minimax.io/v1',MODEL='MiniMax-M3';
const DEPTH={Quick:{chapters:4,sections:'2 to 3',words:'350 to 550',chapterTokens:4200,finalTokens:4500},Detailed:{chapters:6,sections:'3 to 5',words:'700 to 1100',chapterTokens:7000,finalTokens:6500},Expert:{chapters:8,sections:'4 to 7',words:'1000 to 1600',chapterTokens:9000,finalTokens:8000}};

export const getMiniMaxConfig=(env=process.env)=>({apiKey:env.MINIMAX_API_KEY||'',baseUrl:(env.MINIMAX_BASE_URL||BASE).replace(/\/+$/,''),model:env.MINIMAX_MODEL||MODEL});
export function extractJson(text){if(!text||typeof text!=='string')throw new Error('MiniMax returned an empty response.');const raw=text.replace(/<think>[\s\S]*?(?:<\/think>|$)\s*/gi,'').trim(),f=raw.match(/```(?:json)?\s*([\s\S]*?)```/i),candidate=(f?f[1]:raw).trim();const parse=v=>{try{return JSON.parse(v);}catch{const clean=v.replace(/^\s*\.{3}\s*,?\s*$/gm,'').replace(/,\s*([}\]])/g,'$1');if(clean!==v)return JSON.parse(clean);throw new Error('MiniMax response was not valid JSON.');}};try{return parse(candidate);}catch{const a=candidate.indexOf('{'),b=candidate.lastIndexOf('}');if(a>=0&&b>a)return parse(candidate.slice(a,b+1));throw new Error('MiniMax response was not valid JSON.');}}
const responseText=p=>{const c=p?.choices?.[0]?.message?.content;return typeof c==='string'?c:Array.isArray(c)?c.map(x=>typeof x==='string'?x:x?.text||'').join('\n'):'';};
export async function callMiniMaxJson({messages,temperature=.35,maxTokens=4096,thinking=false},options={}){const env=options.env||process.env,fetchImpl=options.fetchImpl||globalThis.fetch,cfg=getMiniMaxConfig(env);if(!cfg.apiKey)throw new Error('MINIMAX_API_KEY is missing. Add it to your .env before using live MiniMax M3 generation.');if(!fetchImpl)throw new Error('Fetch is not available in this Node.js runtime.');const r=await fetchImpl(`${cfg.baseUrl}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${cfg.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:cfg.model,thinking:{type:thinking?'enabled':'disabled'},messages,temperature,max_tokens:maxTokens,stream:false})}),raw=await r.text();let p={};try{p=raw?JSON.parse(raw):{};}catch{p={raw};}if(!r.ok)throw new Error(p?.error?.message||p?.base_resp?.status_msg||raw||`MiniMax request failed with status ${r.status}`);return extractJson(responseText(p));}

export function buildExploreMessages({topic,parentPath=[],depth=1}){return[{role:'system',content:'You are an expert curriculum cartographer. Return only strict JSON. Do not include markdown. Keep labels concise and useful for a recursive subject-learning tree.'},{role:'user',content:JSON.stringify({task:'Generate related subjects for a recursive learning tree.',topic,parentPath,depth,schema:{subjects:[{label:'Concise subject name',children:['Optional concise sub subject names when depth is greater than 1']}]},requirements:['Return 4 to 6 subjects at the current level.','For depth greater than 1, include 2 to 4 children per subject.','Avoid duplicates and overly broad siblings.','Keep every label under 36 characters.','Return JSON object exactly with key subjects.']})}];}

export function buildResearchPlanMessages({topic,selectedItems=[],options={}}){const cfg=DEPTH[options.depth]||DEPTH.Detailed;return[{role:'system',content:'You are a senior research director. Return strict JSON only. Design an investigation, not a curriculum and not one section per mind-map node. The selected tree is scope and context; combine related nodes into a small number of coherent research chapters.'},{role:'user',content:JSON.stringify({task:'Plan one deep research dossier around the central topic.',topic,selectedTreeScope:selectedItems,audience:options.audience||'Intermediate',depth:options.depth||'Detailed',requestedLanguage:options.language||'English',schema:{centralQuestion:'The main question the dossier must answer',scopeSummary:'What is and is not being investigated',thesisAngles:['Cross-cutting analytical angles'],chapters:[{id:'chapter-1',title:'Meaningful research chapter',purpose:'What this chapter must establish',selectedTopics:['Related tree labels combined into the chapter'],questions:['Specific research questions'],queries:['Specific technical, official, academic, or primary-source searches']}]},requirements:[`Create at most ${cfg.chapters} chapters.`,'Combine parent and child nodes; never create one chapter for every selected node.','Cover mechanisms, workflows, architecture, tradeoffs, limitations, practical implications, and comparisons.','Include a synthesis-oriented chapter when useful.','Do not include sources, citations, report prose, or markdown.','Return JSON with centralQuestion, scopeSummary, thesisAngles, and chapters only.']})}];}

export function buildChapterMessages({topic,chapter,evidencePack,options={}}){const cfg=DEPTH[options.depth]||DEPTH.Detailed,ids=(evidencePack?.sources||[]).map(s=>s.id);return[{role:'system',content:'You are a senior analyst writing one chapter of a deep research dossier. Return strict JSON only. Write plain text, not markdown or HTML. Use evidence for named, current, quantitative, comparative, or case-specific claims. Stable expert knowledge may explain established concepts. Never mention sources, searches, evidence coverage, URLs, citations, or source IDs in prose.'},{role:'user',content:JSON.stringify({task:'Write a substantial self-contained research chapter.',topic,chapter,audience:options.audience||'Intermediate',depth:options.depth||'Detailed',includeExamples:options.includeExamples!==false,internalEvidence:evidencePack||{sources:[]},allowedSourceIds:ids,schema:{id:chapter.id,title:chapter.title,thesis:'Precise chapter argument',opening:['Two or three orienting paragraphs'],sections:[{heading:'Analytical subsection',paragraphs:['Detailed paragraphs explaining causal mechanisms, process, architecture, evidence, tradeoffs, failure modes, and implications'],takeaways:['Specific conclusions'],sourceIds:['Internal IDs only']}],comparisonTable:{title:'Optional comparison',columns:['Dimension','Option A','Option B'],rows:[['Row','Comparison','Comparison']],sourceIds:['Internal IDs only']},practicalImplications:['Concrete implications or actions'],limitations:['Important limitations and boundary conditions'],sourceIds:['Union of internal IDs used']},requirements:[`Write approximately ${cfg.words} words.`,`Use ${cfg.sections} analytical subsections.`,'Synthesize evidence instead of summarizing sources one by one.','Prioritize causal mechanisms, workflow details, architecture, tradeoffs, and failure modes.','Do not repeat points across fields.','Return null for comparisonTable unless comparison genuinely helps.','Do not expose sources, citations, publishers, URLs, IDs, confidence, or evidence coverage in prose.','Use only allowed source IDs in sourceIds fields.']})}];}

export function buildDossierSynthesisMessages({topic,selectedItems=[],options={},researchPlan={},chapterDrafts=[]}){return[{role:'system',content:'You are the editor of a high-quality research dossier. Return strict JSON only. Create a coherent answer-first narrative from the chapters. Plain text only, with no markdown, HTML, citations, URLs, source names, source IDs, scores, or research-process commentary.'},{role:'user',content:JSON.stringify({task:'Create the front matter and closing synthesis for one integrated deep research dossier.',topic,selectedTreeScope:selectedItems,audience:options.audience||'Intermediate',depth:options.depth||'Detailed',requestedLanguage:options.language||'English',researchPlan,chapterDrafts:chapterDrafts.map(compactChapter),schema:{title:'Specific dossier title',subtitle:'One-line dossier question or value',executiveSummary:['Three to six substantial answer-first paragraphs'],keyFindings:[{title:'Concise finding',explanation:'Why it matters'}],conclusion:['Cross-chapter synthesis paragraphs'],recommendations:['Specific prioritized recommendations or decision principles'],openQuestions:['Important unresolved questions']},requirements:['Lead with the answer.','Synthesize patterns, tensions, dependencies, and tradeoffs across chapters.','Do not list every selected node.','Do not mention sources, citations, coverage, or research process.','Use the requested language throughout.']})}];}
export const buildAnalyzeMessages=buildDossierSynthesisMessages;

export async function exploreWithMiniMax(payload,options){const r=await callMiniMaxJson({messages:buildExploreMessages(payload),temperature:.25,maxTokens:2500,thinking:false},options);if(!Array.isArray(r.subjects))throw new Error('MiniMax explore response did not include a subjects array.');return r;}

export async function analyzeWithMiniMax(payload,options={}){const depth=payload?.options?.depth||'Detailed',cfg=DEPTH[depth]||DEPTH.Detailed,provider=options.researchProvider||collectDossierResearch;let plan;try{plan=normalizeResearchPlan(await callMiniMaxJson({messages:buildResearchPlanMessages(payload),temperature:.18,maxTokens:5000,thinking:true},options),payload);}catch{plan=buildFallbackResearchPlan(payload);}let research;try{research=await provider({...payload,researchPlan:plan},options);}catch{research={overview:{sources:[]},chapters:[]};}research=normalizeResearch(research,plan);const chapters=await mapConcurrent(plan.chapters,options.chapterConcurrency||2,async(chapter,index)=>{const evidence=research.chapters[index]||{id:chapter.id,title:chapter.title,sources:[]};try{let draft=await callMiniMaxJson({messages:buildChapterMessages({topic:payload.topic,chapter,evidencePack:evidence,options:payload.options}),temperature:.2,maxTokens:cfg.chapterTokens,thinking:true},options),valid=validateChapterResult(draft,{chapter,evidencePack:evidence,depth});if(!valid.valid){draft=await repairChapter(draft,valid.errors,{payload,chapter,evidence,cfg,options});valid=validateChapterResult(draft,{chapter,evidencePack:evidence,depth});}return valid.valid?normalizeChapter(draft,{chapter,evidence}):fallbackChapter(payload.topic,chapter,evidence,payload.options);}catch{return fallbackChapter(payload.topic,chapter,evidence,payload.options);}});let synthesis;try{synthesis=await callMiniMaxJson({messages:buildDossierSynthesisMessages({...payload,researchPlan:plan,chapterDrafts:chapters}),temperature:.18,maxTokens:cfg.finalTokens,thinking:true},options);}catch{synthesis=fallbackSynthesis(payload.topic,plan,chapters);}const assembled={...synthesis,researchQuestion:plan.centralQuestion,scopeSummary:plan.scopeSummary,chapters},valid=validateAnalysisResult(assembled,{researchPlan:plan});return normalizeAnalysisResult(valid.valid?assembled:{...fallbackSynthesis(payload.topic,plan,chapters),researchQuestion:plan.centralQuestion,scopeSummary:plan.scopeSummary,chapters},{topic:payload.topic,researchPlan:plan});}

async function repairChapter(draft,errors,{payload,chapter,evidence,cfg,options}){return callMiniMaxJson({messages:[...buildChapterMessages({topic:payload.topic,chapter,evidencePack:evidence,options:payload.options}),{role:'assistant',content:JSON.stringify(draft)},{role:'user',content:JSON.stringify({task:'Repair the chapter JSON without shortening the substantive analysis.',validationErrors:errors,requirements:['Return complete corrected JSON only.','Keep plain text and remove citations or markup.','Use only allowed source IDs.','Preserve depth and eliminate repetition.']})}],temperature:.1,maxTokens:cfg.chapterTokens,thinking:true},options);}

export function validateChapterResult(result,{chapter={},evidencePack={},depth='Detailed'}={}){const errors=[];if(!result||typeof result!=='object')return{valid:false,errors:['Chapter must be an object.']};if(key(result.id)!==key(chapter.id))errors.push('Chapter id changed.');if(key(result.title)!==key(chapter.title))errors.push('Chapter title changed.');if(!Array.isArray(result.sections)||!result.sections.length)errors.push('Chapter sections must be a non-empty array.');const prose=[result.title,result.thesis,...arr(result.opening),...arr(result.practicalImplications),...arr(result.limitations)];for(const s of arr(result.sections))prose.push(s?.heading,...arr(s?.paragraphs),...arr(s?.takeaways));if(result.comparisonTable)prose.push(result.comparisonTable.title,...arr(result.comparisonTable.columns),...arr(result.comparisonTable.rows).flatMap(arr));if(prose.some(markup))errors.push('Chapter contains HTML, markdown, links, or citation-like markup.');const allowed=new Set((evidencePack.sources||[]).map(s=>s.id));for(const sourceId of sourceIds(result))if(!allowed.has(sourceId))errors.push(`Chapter contains unknown source ID ${sourceId}.`);const min=depth==='Expert'?3:depth==='Quick'?1:2;if(arr(result.sections).length<min)errors.push(`Chapter requires at least ${min} analytical sections.`);const paragraphCount=arr(result.opening).length+arr(result.sections).reduce((n,s)=>n+arr(s?.paragraphs).length,0);if(paragraphCount<(depth==='Quick'?3:5))errors.push('Chapter is too shallow.');return{valid:!errors.length,errors};}
export function validateAnalysisResult(result,{researchPlan={}}={}){const errors=[];if(!result||typeof result!=='object')return{valid:false,errors:['Response must be an object.']};if(!Array.isArray(result.chapters))errors.push('chapters must be an array.');if(markup(result.title)||markup(result.subtitle))errors.push('Title and subtitle must be plain text.');for(const value of [...arr(result.executiveSummary),...arr(result.conclusion),...arr(result.recommendations),...arr(result.openQuestions)])if(markup(value))errors.push('Dossier contains markup.');if(Array.isArray(result.chapters)&&Array.isArray(researchPlan.chapters)){if(result.chapters.length!==researchPlan.chapters.length)errors.push('Chapter count changed.');researchPlan.chapters.forEach((chapter,index)=>{if(key(result.chapters?.[index]?.id)!==key(chapter.id))errors.push(`Chapter ${index+1} id changed.`);});}return{valid:!errors.length,errors};}

export function normalizeAnalysisResult(result,{topic='Learning Topic',researchPlan={}}={}){return{title:plain(result.title||`${topic} Research Dossier`),subtitle:plain(result.subtitle||researchPlan.centralQuestion||''),researchQuestion:plain(result.researchQuestion||researchPlan.centralQuestion||topic),scopeSummary:plain(result.scopeSummary||researchPlan.scopeSummary||''),executiveSummary:paragraphs(result.executiveSummary),keyFindings:arr(result.keyFindings).map(finding=>({title:plain(finding?.title||''),explanation:plain(finding?.explanation||finding||'')})).filter(finding=>finding.title||finding.explanation),chapters:arr(result.chapters).map(clientChapter),conclusion:paragraphs(result.conclusion),recommendations:list(result.recommendations,12),openQuestions:list(result.openQuestions,12)};}
export function normalizeResearchPlan(plan,{topic='Learning Topic',selectedItems=[],options={}}={}){const fallback=buildFallbackResearchPlan({topic,selectedItems,options}),max=(DEPTH[options.depth]||DEPTH.Detailed).chapters,chapters=arr(plan?.chapters).slice(0,max).map((chapter,index)=>({id:id(chapter?.id||`chapter-${index+1}`),title:plain(chapter?.title||fallback.chapters[index]?.title||`Chapter ${index+1}`),purpose:plain(chapter?.purpose||''),selectedTopics:uniq(chapter?.selectedTopics),questions:list(chapter?.questions,5),queries:list(chapter?.queries,7)})).filter(chapter=>chapter.title);return{centralQuestion:plain(plan?.centralQuestion||fallback.centralQuestion),scopeSummary:plain(plan?.scopeSummary||fallback.scopeSummary),thesisAngles:list(plan?.thesisAngles,8),chapters:chapters.length?uniqueChapterIds(chapters):fallback.chapters};}
export function buildFallbackResearchPlan({topic='Learning Topic',selectedItems=[],options={}}={}){const max=(DEPTH[options.depth]||DEPTH.Detailed).chapters,root=selectedItems[0]?.path?.[0]||topic,groups=new Map();for(const item of selectedItems){const path=Array.isArray(item.path)?item.path:[root,item.label];if(key(item.label)===key(root)&&path.length<=1)continue;const branch=path.length>1?path[1]:item.label;if(!groups.has(branch))groups.set(branch,[]);groups.get(branch).push(item.label);}let entries=[...groups.entries()];if(!entries.length)entries=[['Foundations and scope',[topic]],['Mechanisms and workflow',[topic]],['Tools and implementation',[topic]],['Tradeoffs, risks, and limitations',[topic]]];const chapters=entries.slice(0,max).map(([title,labels],index)=>({id:`chapter-${index+1}`,title:plain(title),purpose:`Explain ${title} as part of a coherent investigation of ${topic}, including mechanisms, tradeoffs, and practical implications.`,selectedTopics:uniq(labels),questions:[`What are the essential mechanisms and concepts in ${title}?`,`How is ${title} applied in practice?`,`What limitations, tradeoffs, and failure modes matter most?`],queries:uniq([`${topic} ${title} technical overview`,`${title} mechanisms workflow`,`${title} tools comparison limitations`,`${title} case study evidence`])}));return{centralQuestion:`What must be understood to evaluate and apply ${topic} rigorously?`,scopeSummary:`An integrated investigation of ${topic}, using the selected mind-map branches as scope rather than as a section checklist.`,thesisAngles:['mechanisms','workflow','tradeoffs','practical implications','limitations'],chapters};}
export function getSelectionKind(item,selectedItems=[]){return selectedItems.some(candidate=>candidate!==item&&prefix(item.path,candidate.path))?'overview':'detail';}

function normalizeResearch(value,plan){if(Array.isArray(value))return{overview:{sources:[]},chapters:plan.chapters.map((chapter,index)=>({id:chapter.id,title:chapter.title,sources:value[index]?.sources||[],coverage:value[index]?.coverage||'insufficient',confidence:value[index]?.confidence||0}))};return{overview:value?.overview||{sources:[]},chapters:plan.chapters.map((chapter,index)=>({id:chapter.id,title:chapter.title,purpose:chapter.purpose,questions:chapter.questions,sources:value?.chapters?.[index]?.sources||[],coverage:value?.chapters?.[index]?.coverage||'insufficient',confidence:value?.chapters?.[index]?.confidence||0}))};}
function normalizeChapter(result,{chapter,evidence}){const allowed=new Set((evidence.sources||[]).map(source=>source.id));return{id:chapter.id,title:chapter.title,thesis:plain(result.thesis||''),opening:paragraphs(result.opening),sections:arr(result.sections).map(section=>({heading:plain(section?.heading||''),paragraphs:paragraphs(section?.paragraphs),takeaways:list(section?.takeaways,5),sourceIds:uniq(section?.sourceIds).filter(sourceId=>allowed.has(sourceId))})).filter(section=>section.heading||section.paragraphs.length),comparisonTable:table(result.comparisonTable,allowed),practicalImplications:list(result.practicalImplications,10),limitations:list(result.limitations,10),sourceIds:uniq(result.sourceIds).filter(sourceId=>allowed.has(sourceId))};}
function fallbackChapter(topic,chapter,evidence,options={}){const notes=(evidence.sources||[]).slice(0,6).map(source=>plain(source.note)).filter(Boolean),opening=[`${chapter.title} is a core part of understanding ${topic}. This chapter focuses on mechanisms, workflow, tradeoffs, and practical consequences.`,notes[0]||'The analysis uses established domain knowledge while avoiding unsupported current or quantitative claims.'],groups=notes.length?chunk(notes,2):[[]],sections=groups.slice(0,options.depth==='Quick'?2:4).map((group,index)=>({heading:['Mechanisms and operating model','Workflow and practical use','Tradeoffs and failure modes','Implications'][index],paragraphs:group.length?group:[`${chapter.title} should be evaluated by tracing inputs, transformations, outputs, dependencies, and assumptions.`,`Its value depends on fit with the environment, available tooling, observability, and the cost of false conclusions.`],takeaways:[],sourceIds:[]}));while(sections.length<(options.depth==='Quick'?1:2))sections.push({heading:'Practical implications',paragraphs:['The technique should be tied to a specific decision and validated with complementary observations.','Tool output is evidence to interpret, not a substitute for reasoning about the target system.'],takeaways:[],sourceIds:[]});return{id:chapter.id,title:chapter.title,thesis:`${chapter.title} is most useful as part of an integrated investigation rather than as an isolated technique.`,opening,sections,comparisonTable:null,practicalImplications:[`Define the decision ${chapter.title} must support before choosing methods or tools.`,'Combine complementary evidence and test assumptions against observed behavior.'],limitations:['Results depend on the quality and representativeness of evidence.','Stable conceptual knowledge should not be mistaken for current case-specific facts.'],sourceIds:[]};}
function fallbackSynthesis(topic,plan,chapters){return{title:`${topic} Research Dossier`,subtitle:plan.centralQuestion,executiveSummary:[`This dossier treats ${topic} as one integrated investigation rather than disconnected topic summaries.`,`The selected mind-map branches define scope, while the chapters explain mechanisms, workflow, tradeoffs, and implications in a coherent sequence.`],keyFindings:chapters.slice(0,8).map(chapter=>({title:chapter.title,explanation:chapter.thesis||chapter.opening?.[0]||''})),conclusion:[`${topic} should be evaluated through connected mechanisms and decisions, not isolated labels.`,'The strongest conclusions combine conceptual understanding, observed evidence, comparison, and explicit limits.'],recommendations:uniq(chapters.flatMap(chapter=>chapter.practicalImplications||[])).slice(0,10),openQuestions:uniq(chapters.flatMap(chapter=>chapter.limitations||[])).slice(0,8)};}
function compactChapter(chapter){return{id:chapter.id,title:chapter.title,thesis:chapter.thesis,opening:arr(chapter.opening).slice(0,2),sectionSummaries:arr(chapter.sections).map(section=>({heading:section.heading,paragraphs:arr(section.paragraphs).slice(0,2),takeaways:arr(section.takeaways)})),practicalImplications:chapter.practicalImplications,limitations:chapter.limitations};}
function clientChapter(chapter){return{id:id(chapter?.id||''),title:plain(chapter?.title||''),thesis:plain(chapter?.thesis||''),opening:paragraphs(chapter?.opening),sections:arr(chapter?.sections).map(section=>({heading:plain(section?.heading||''),paragraphs:paragraphs(section?.paragraphs),takeaways:list(section?.takeaways,6)})).filter(section=>section.heading||section.paragraphs.length),comparisonTable:table(chapter?.comparisonTable),practicalImplications:list(chapter?.practicalImplications,12),limitations:list(chapter?.limitations,12)};}
function table(value,allowed=null){if(!value||typeof value!=='object')return null;const columns=list(value.columns,8),rows=arr(value.rows).map(row=>arr(row).map(plain).slice(0,columns.length)).filter(row=>row.length);if(columns.length<2||!rows.length)return null;return{title:plain(value.title||''),columns,rows,...(allowed?{sourceIds:uniq(value.sourceIds).filter(sourceId=>allowed.has(sourceId))}:{})};}
function sourceIds(result){return uniq([...arr(result?.sourceIds),...arr(result?.sections).flatMap(section=>arr(section?.sourceIds)),...arr(result?.comparisonTable?.sourceIds)]);}
function markup(value){const text=String(value||'');return /<\/?[a-z][^>]*>|&lt;\/?[a-z]|```|\[[^\]]+\]\([^)]*\)|https?:\/\//i.test(text);}
const arr=value=>Array.isArray(value)?value:value==null?[]:[value];
const paragraphs=value=>uniq(arr(value).flatMap(entry=>String(entry||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>/gi,'\n\n').replace(/<[^>]*>/g,' ').split(/\n\s*\n+/).map(plain))).filter(Boolean);
const list=(value,max=20)=>uniq(arr(value).map(plain)).filter(Boolean).slice(0,max);
const plain=value=>String(value||'').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#0?39;/gi,"'").replace(/&amp;/gi,'&').replace(/<[^>]*>/g,' ').replace(/[`*_#]+/g,'').replace(/\s+/g,' ').trim();
const key=value=>plain(value).toLowerCase().replace(/[^a-z0-9]+/g,'');
const id=value=>plain(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'chapter';
function uniq(values=[]){const seen=new Set(),out=[];for(const value of arr(values)){const text=String(value||'').trim(),normalized=text.toLowerCase();if(text&&!seen.has(normalized)){seen.add(normalized);out.push(text);}}return out;}
function uniqueChapterIds(chapters){const seen=new Set();return chapters.map((chapter,index)=>{let chapterId=id(chapter.id||`chapter-${index+1}`),base=chapterId,suffix=2;while(seen.has(chapterId))chapterId=`${base}-${suffix++}`;seen.add(chapterId);return{...chapter,id:chapterId};});}
const prefix=(parent=[],child=[])=>child.length>parent.length&&parent.every((value,index)=>key(value)===key(child[index]));
const chunk=(values,size)=>Array.from({length:Math.ceil(values.length/size)},(_,index)=>values.slice(index*size,index*size+size));
async function mapConcurrent(items,concurrency,mapper){if(!items.length)return[];const results=new Array(items.length);let next=0;const workers=Array.from({length:Math.min(Math.max(concurrency,1),items.length)},async()=>{while(next<items.length){const index=next++;results[index]=await mapper(items[index],index);}});await Promise.all(workers);return results;}
